[package]
name = "ca_lexer_flex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
cc = "1.0.71"
bindgen = "0.59.1"