[package]
name = "ca_backend_llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ca_uir = {path="../ca_uir"}
inkwell = "0.1.0-beta.4"
debug-cell = "0.1.1"
