[package]
name = "ca_backend_llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ca_ast = {path="../ca_ast"}

inkwell = "0.1.0-llvm8sample"